{{- if .Values.mediaShare.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .Release.Namespace }}-{{ .Release.Name }}-media-share
  labels:
    namespace: {{ .Release.Namespace }}
    release: {{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  - ReadOnlyMany
  capacity:
    storage: {{ .Values.nfsShare.capacity.storage }}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: media-dir
    namespace: {{ .Release.Namespace }}
  nfs:
    path: {{ .Values.mediaShare.path }}
    server: {{ .Values.mediaShare.server }}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
...
{{- end }}
