# Generated by Django 2.2.15 on 2020-09-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0034_auto_20200512_1431'),
        ('geonode_dominode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Command name')),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
                ('command', models.TextField(verbose_name='Command')),
                ('groups', models.ManyToManyField(to='groups.GroupProfile')),
            ],
            options={
                'permissions': [('execute_cli', 'Can Execute CLI')],
            },
        ),
        migrations.DeleteModel(
            name='CLIGroup',
        ),
    ]
